FROM nginx:latest
#엔진엑스 도커파일
RUN apt-get update && apt install -y nginx vim
#RUN echo "\ndeamon off;" >> /etc/nginx/nginx.conf
#RUN chown -R www-data:www-data /var/lib/nginx

COPY nginx.conf /etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/sites-available/django
RUN mkdir /etc/nginx/sites-enabled
RUN ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/django

CMD ["nginx"]

EXPOSE 80
EXPOSE 443